name: flutter_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # State
  get: ^4.3.6

  flutter_svg: ^0.22.0

  # WebView
  flutter_inappwebview: ^5.3.2

  # 设备及包详情
  device_info: ^2.0.0
  package_info: ^2.0.0

  # Data
  json_annotation: ^4.0.1
  dio: ^4.0.0
  # Dio Cookie管理
  dio_cookie_manager: ^2.0.0
  dio_http_cache:
    git: https://github.com/hurshi/dio-http-cache
  cookie_jar: ^3.0.1
  # 信息储存
  shared_preferences: ^2.0.5
  # 本地json对象存储
  localstorage: ^4.0.0+1

  # Html Encoder/Decoder
  # html_unescape: ^1.0.2
  # 解析html标签
  # flutter_html: ^2.0.0-nullsafety.0

  # 集合
  collection: ^1.15.0
  #  crypto: ^2.1.5

  #带缓存的图片加载
  extended_image: ^4.0.1
  # 扩展text
  extended_text: ^5.0.5
  
  # 下拉刷新
  pull_to_refresh: ^2.0.0
  # 轮播图
  flutter_swiper_null_safety: ^1.0.2
  # 瀑布流列表
  # flutter_staggered_grid_view: ^0.3.2

  # 更新展示支持mark_down
  # flutter_markdown: ^0.5.0
  # 动画
  # flare_flutter: ^2.0.6

  # third_app
  # url_launcher: ^5.7.10 #启动第三方app
  # share: 0.6.5+4 #分享
  # launch_review: ^2.0.0 #打开应用市场
  open_file: ^3.2.0

  # android权限弹窗
  permission_handler: 8.1.6

  # 消息总线
  event_bus: ^2.0.0

  # 目录获取
  path_provider: ^2.0.1

  # 图片压缩
  flutter_image_compress: ^1.0.0

  # 对话框
  awesome_dialog: ^2.0.0

  # 点击外部隐藏软键盘
  keyboard_dismisser: ^2.0.0

  # 文件选取
  wechat_assets_picker: ^5.1.3

  # 列表动画
  flutter_staggered_animations: ^1.0.0

  # 用于DateFormat
  intl: ^0.17.0
  # loading动画
  flutter_easyloading: 3.0.3

  # 自动缩放字体
  auto_size_text: ^3.0.0-nullsafety.0

  # 对话框
  adaptive_dialog: ^1.0.0

  # 屏幕适配
  flutter_autosize_screen: ^1.0.1

  # 加载动画
  loading_indicator: 3.0.2

  # websocket
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.1
  # json 序列化
  json_serializable: ^4.1.1

flutter:

  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  assets:
    - assets/icons/
    - assets/images/